### ISSUE TITLE
Usage for run_decoden with no arguments

### ISSUE THREAD

**Issue by MarekGierlinski** [ntanmayee/DecoDen#3]
When running `run_decoden.py` with no arguments, one would expect a  'usage' comment. Instead, there is an error with some mysterious hard-wired directory:

```
> python run_decoden.py

██████╗ ███████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗
██╔══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝████╗  ██║
██║  ██║█████╗  ██║     ██║   ██║██║  ██║█████╗  ██╔██╗ ██║
██║  ██║██╔══╝  ██║     ██║   ██║██║  ██║██╔══╝  ██║╚██╗██║
██████╔╝███████╗╚██████╗╚██████╔╝██████╔╝███████╗██║ ╚████║
╚═════╝ ╚══════╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝
-----------------------------------------------------------
Narendra, T., Visonà, G., de Jesus Cardona, C., & Schweikert,
G. (2022). Multi-histone ChIP-Seq Analysis with DecoDen. bioRxiv.
-----------------------------------------------------------

Traceback (most recent call last):
  File "/cluster/gjb_lab/mgierlinski/projects/decoden_test/run_decoden.py", line 129, in <module>
    main(args)
  File "/cluster/gjb_lab/mgierlinski/projects/decoden_test/run_decoden.py", line 24, in main
    with open(args.files_reference, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '../DecoDen_GV/data/shallow_e114_200bp_bedGraph_files/sample_files.json'
```

**Comment by ntanmayee** [comment]
Errors in parsing arguments in `run_decoden.py` -  there are hard coded arguments and required arguments are not specified correctly. Issues #7 #6 are also related to this. 

Same error is also found in `run_decoden_replicates.py`.
